### ISSUE TITLE
REF prefixes differ for indels across vcfs

### ISSUE THREAD

**Issue by qhelleu** [hsinnan75/MapCaller#39]
Hello,
I ran MapCaller (version 0.9.9.d) across a bunch of samples with the following command:

MapCaller -i $GENOME -f ./pop_fastq/${line}_1.fastq.gz -f2 ./pop_fastq/${line}_2.fastq.gz -t $SLURM_NTASKS -ploidy 1 -vcf ./MC_Out/${line}.vcf

And when I tried to merge all the vcf files with vcf-merge, I discovered that REF is different for some indels at the same position across some samples. 
I get such error:
The REF prefixes differ: AAGA vs AGAA (4,4) 
Here, the chr1 POS 283 REF is AGAA in one sample and AAGA in two others.

Can you tell me if it's normal and how I can solve such discrepancies?

Thanks,
Quentin

**Comment by hsinnan75** [comment]
Hello, thanks for reporting this bug. I found this bug earlier. They are all deletion types. I made a mistake when determine the position of a deletion event in a reverse strand alignment. This bug was fixed. Please update MapCaller to the latest version and try again. If you still have the same error, please let me know. Thank you very much.

**Comment by qhelleu** [comment]
Hello,
I tried again with the version 0.9.9.18 (from a git clone yesterday) and it looks like the error is still present!

Thanks,
Best,
Quentin

**Comment by hsinnan75** [comment]
I'll check the codes again. Thank you!

**Comment by hsinnan75** [comment]
Hello, I found the bug. It happens when the deletion events occur at both forward and reverse strands, and the two strands produces different alignments due to ambiguous alignment, and the deletion sequences are extracted from sequence alignments. MapCaller outputs one of them according to their frequency. Moreover, the different strands could produce same position in some cases since they are calculated from different direction. 

To be honest, the orientation and ambiguous alignment complicate the position calculation. I'll come up with a new solution and update MapCaller as soon as possible. Thank you for identifying this error.

**Comment by hsinnan75** [comment]
Hi, I've updated MapCaller to v0.9.9.19. Could you please run MapCaller again? Thank you!!  Fingers crossed.

**Comment by qhelleu** [comment]
Great! I try it ASAP.
Thanks!

**Comment by qhelleu** [comment]
Hello,
I reran MapCaller with the version 0.9.9.19, and it looks like the problem is solved!
Great, thanks!

**Comment by hsinnan75** [comment]
Thank you for the effort.
